### NumPy Broadcasting Examples

---

#### Scenario 1: Compatible Shapes (Equal Dimensions)

In [1]:
import numpy as np

A = np.array([1, 2, 3])  # Shape (3,)
B = np.array([4, 5, 6])  # Shape (3,)
result = A + B
print(result)  # [5, 7, 9]

[5 7 9]


In [2]:
A.shape

(3,)

In [3]:
B.shape

(3,)

In [4]:
result.shape

(3,)

#### Scenario 2: Compatible Shapes (One Dimension is 1)

In [5]:
A = np.array([[1], [2], [3]])     # Shape (3,1)
B = np.array([[4, 5, 6]])         # Shape (1,3)

# A + B   Works, B is broadcast along the first dimension, A along the second

result = A + B
print(result)
# [[5, 6, 7],
#  [6, 7, 8],
#  [7, 8, 9]]

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [7]:
A

array([[1],
       [2],
       [3]])

In [8]:
B

array([[4, 5, 6]])

#### Scenario 3: Compatible Shapes (Fewer Dimensions)

In [9]:
A = np.array([1, 2, 3])   # A (3,)
B = np.array([[4, 5, 6],   # B (3, 3)
              [7, 8, 9],
              [10, 11, 12]])

#A + B  # Works, A is treated as (1, 3) and then broadcast along the first dimension

result = A + B
print(result)
# [[ 5,  7,  9],
#  [ 8, 10, 12],
#  [11, 13, 15]]

[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [10]:
A

array([1, 2, 3])

#### Scenario 4: Scalar Operation

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
scalar = 2
result = A * scalar   # Works, scalar is broadcast to the shape of A
print(result)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### When Vector Broadcasting Does NOT Work

#### Incompatible Shapes

In [ ]:
A = np.array([1, 2, 3])  # Shape (3,)
B = np.array([4, 5])     # Shape (2,)
A + B  # Fails, the second dimensions (size 3 and 2) are incompatible

#### Example: Broadcasting Works with Column Vector

In [ ]:
import numpy as np
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])    # Shape (3, 2)
B = np.array([[7], [8], [9]])  # Shape (3, 1)
result = A + B
print(result)
# [[ 8,  9],
#  [11, 12],
#  [14, 15]]

[[ 8  9]
 [11 12]
 [14 15]]


In [ ]:
B

array([[7],
       [8],
       [9]])

In [ ]:
row_vec=np.array([[1,2,3]])

In [ ]:
row_vec

array([[1, 2, 3]])

In [ ]:
np.dot(A,B)

ValueError: shapes (3,2) and (3,1) not aligned: 2 (dim 1) != 3 (dim 0)

#### Example: Broadcasting Fails Due to Mismatched Shapes

In [ ]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])      # Shape (3,2)
B = np.array([[7, 8, 9],
              [10, 11, 12]]) # Shape (2,3)
# A + B  # Uncommenting this will raise ValueError: operands could not be broadcast together

### Summary

To determine if broadcasting will work, compare shapes from trailing dimensions backwards. Broadcasting is possible when:

- The dimensions are equal, or
- One of the dimensions is 1

Otherwise, broadcasting will fail, resulting in a ValueError due to incompatible shapes.